language: node_js
node_js:
  - stable
cache:
  yarn: true

script: yarn test

before_deploy: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "S3 Bucket"
  local_dir: dist
  upload-dir: css-in-js
  skip_cleanup: true
  acl: public_read
  on:
    branch: master
